/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShowcaseRouteImport } from './routes/showcase'
import { Route as GuestRouteRouteImport } from './routes/_guest/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as GuestSignupRouteImport } from './routes/_guest/signup'
import { Route as GuestLoginRouteImport } from './routes/_guest/login'
import { Route as AuthAppRouteRouteImport } from './routes/_auth/app/route'
import { Route as AuthAdminRouteRouteImport } from './routes/_auth/admin/route'
import { Route as AuthAppIndexRouteImport } from './routes/_auth/app/index'
import { Route as AuthAdminIndexRouteImport } from './routes/_auth/admin/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthGIdRouteImport } from './routes/_auth/g.$id'
import { Route as AuthAppPlayersRouteImport } from './routes/_auth/app/players'
import { Route as AuthAppPlayerPairsRouteImport } from './routes/_auth/app/playerPairs'
import { Route as AuthAdminUsersRouteImport } from './routes/_auth/admin/users'
import { Route as AuthAppTournamentsIndexRouteImport } from './routes/_auth/app/tournaments/index'
import { Route as AuthAppMatchesMatchIdRouteImport } from './routes/_auth/app/matches/$matchId'
import { Route as AuthAppTournamentsSlugIndexRouteImport } from './routes/_auth/app/tournaments/$slug.index'
import { Route as AuthAppBracketsBracketIdIndexRouteImport } from './routes/_auth/app/brackets/$bracketId.index'
import { Route as AuthAppTournamentsSlugCategoriesCategoryIdIndexRouteImport } from './routes/_auth/app/tournaments/$slug.categories.$categoryId.index'

const ShowcaseRoute = ShowcaseRouteImport.update({
  id: '/showcase',
  path: '/showcase',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRouteRoute = GuestRouteRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/_public/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestSignupRoute = GuestSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => GuestRouteRoute,
} as any)
const GuestLoginRoute = GuestLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GuestRouteRoute,
} as any)
const AuthAppRouteRoute = AuthAppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAdminRouteRoute = AuthAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAppIndexRoute = AuthAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAdminIndexRoute = AuthAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAdminRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGIdRoute = AuthGIdRouteImport.update({
  id: '/g/$id',
  path: '/g/$id',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAppPlayersRoute = AuthAppPlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppPlayerPairsRoute = AuthAppPlayerPairsRouteImport.update({
  id: '/playerPairs',
  path: '/playerPairs',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAdminUsersRoute = AuthAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthAdminRouteRoute,
} as any)
const AuthAppTournamentsIndexRoute = AuthAppTournamentsIndexRouteImport.update({
  id: '/tournaments/',
  path: '/tournaments/',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppMatchesMatchIdRoute = AuthAppMatchesMatchIdRouteImport.update({
  id: '/matches/$matchId',
  path: '/matches/$matchId',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppTournamentsSlugIndexRoute =
  AuthAppTournamentsSlugIndexRouteImport.update({
    id: '/tournaments/$slug/',
    path: '/tournaments/$slug/',
    getParentRoute: () => AuthAppRouteRoute,
  } as any)
const AuthAppBracketsBracketIdIndexRoute =
  AuthAppBracketsBracketIdIndexRouteImport.update({
    id: '/brackets/$bracketId/',
    path: '/brackets/$bracketId/',
    getParentRoute: () => AuthAppRouteRoute,
  } as any)
const AuthAppTournamentsSlugCategoriesCategoryIdIndexRoute =
  AuthAppTournamentsSlugCategoriesCategoryIdIndexRouteImport.update({
    id: '/tournaments/$slug/categories/$categoryId/',
    path: '/tournaments/$slug/categories/$categoryId/',
    getParentRoute: () => AuthAppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/showcase': typeof ShowcaseRoute
  '/admin': typeof AuthAdminRouteRouteWithChildren
  '/app': typeof AuthAppRouteRouteWithChildren
  '/login': typeof GuestLoginRoute
  '/signup': typeof GuestSignupRoute
  '/admin/users': typeof AuthAdminUsersRoute
  '/app/playerPairs': typeof AuthAppPlayerPairsRoute
  '/app/players': typeof AuthAppPlayersRoute
  '/g/$id': typeof AuthGIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/': typeof AuthAdminIndexRoute
  '/app/': typeof AuthAppIndexRoute
  '/app/matches/$matchId': typeof AuthAppMatchesMatchIdRoute
  '/app/tournaments/': typeof AuthAppTournamentsIndexRoute
  '/app/brackets/$bracketId/': typeof AuthAppBracketsBracketIdIndexRoute
  '/app/tournaments/$slug/': typeof AuthAppTournamentsSlugIndexRoute
  '/app/tournaments/$slug/categories/$categoryId/': typeof AuthAppTournamentsSlugCategoriesCategoryIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/showcase': typeof ShowcaseRoute
  '/login': typeof GuestLoginRoute
  '/signup': typeof GuestSignupRoute
  '/admin/users': typeof AuthAdminUsersRoute
  '/app/playerPairs': typeof AuthAppPlayerPairsRoute
  '/app/players': typeof AuthAppPlayersRoute
  '/g/$id': typeof AuthGIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin': typeof AuthAdminIndexRoute
  '/app': typeof AuthAppIndexRoute
  '/app/matches/$matchId': typeof AuthAppMatchesMatchIdRoute
  '/app/tournaments': typeof AuthAppTournamentsIndexRoute
  '/app/brackets/$bracketId': typeof AuthAppBracketsBracketIdIndexRoute
  '/app/tournaments/$slug': typeof AuthAppTournamentsSlugIndexRoute
  '/app/tournaments/$slug/categories/$categoryId': typeof AuthAppTournamentsSlugCategoriesCategoryIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_guest': typeof GuestRouteRouteWithChildren
  '/showcase': typeof ShowcaseRoute
  '/_auth/admin': typeof AuthAdminRouteRouteWithChildren
  '/_auth/app': typeof AuthAppRouteRouteWithChildren
  '/_guest/login': typeof GuestLoginRoute
  '/_guest/signup': typeof GuestSignupRoute
  '/_public/': typeof PublicIndexRoute
  '/_auth/admin/users': typeof AuthAdminUsersRoute
  '/_auth/app/playerPairs': typeof AuthAppPlayerPairsRoute
  '/_auth/app/players': typeof AuthAppPlayersRoute
  '/_auth/g/$id': typeof AuthGIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_auth/admin/': typeof AuthAdminIndexRoute
  '/_auth/app/': typeof AuthAppIndexRoute
  '/_auth/app/matches/$matchId': typeof AuthAppMatchesMatchIdRoute
  '/_auth/app/tournaments/': typeof AuthAppTournamentsIndexRoute
  '/_auth/app/brackets/$bracketId/': typeof AuthAppBracketsBracketIdIndexRoute
  '/_auth/app/tournaments/$slug/': typeof AuthAppTournamentsSlugIndexRoute
  '/_auth/app/tournaments/$slug/categories/$categoryId/': typeof AuthAppTournamentsSlugCategoriesCategoryIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/showcase'
    | '/admin'
    | '/app'
    | '/login'
    | '/signup'
    | '/admin/users'
    | '/app/playerPairs'
    | '/app/players'
    | '/g/$id'
    | '/api/auth/$'
    | '/admin/'
    | '/app/'
    | '/app/matches/$matchId'
    | '/app/tournaments/'
    | '/app/brackets/$bracketId/'
    | '/app/tournaments/$slug/'
    | '/app/tournaments/$slug/categories/$categoryId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/showcase'
    | '/login'
    | '/signup'
    | '/admin/users'
    | '/app/playerPairs'
    | '/app/players'
    | '/g/$id'
    | '/api/auth/$'
    | '/admin'
    | '/app'
    | '/app/matches/$matchId'
    | '/app/tournaments'
    | '/app/brackets/$bracketId'
    | '/app/tournaments/$slug'
    | '/app/tournaments/$slug/categories/$categoryId'
  id:
    | '__root__'
    | '/_auth'
    | '/_guest'
    | '/showcase'
    | '/_auth/admin'
    | '/_auth/app'
    | '/_guest/login'
    | '/_guest/signup'
    | '/_public/'
    | '/_auth/admin/users'
    | '/_auth/app/playerPairs'
    | '/_auth/app/players'
    | '/_auth/g/$id'
    | '/api/auth/$'
    | '/_auth/admin/'
    | '/_auth/app/'
    | '/_auth/app/matches/$matchId'
    | '/_auth/app/tournaments/'
    | '/_auth/app/brackets/$bracketId/'
    | '/_auth/app/tournaments/$slug/'
    | '/_auth/app/tournaments/$slug/categories/$categoryId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  GuestRouteRoute: typeof GuestRouteRouteWithChildren
  ShowcaseRoute: typeof ShowcaseRoute
  PublicIndexRoute: typeof PublicIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/showcase': {
      id: '/showcase'
      path: '/showcase'
      fullPath: '/showcase'
      preLoaderRoute: typeof ShowcaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest/signup': {
      id: '/_guest/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof GuestSignupRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_guest/login': {
      id: '/_guest/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof GuestLoginRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_auth/app': {
      id: '/_auth/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthAppRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/admin': {
      id: '/_auth/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthAdminRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/app/': {
      id: '/_auth/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthAppIndexRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/admin/': {
      id: '/_auth/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthAdminIndexRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/g/$id': {
      id: '/_auth/g/$id'
      path: '/g/$id'
      fullPath: '/g/$id'
      preLoaderRoute: typeof AuthGIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/app/players': {
      id: '/_auth/app/players'
      path: '/players'
      fullPath: '/app/players'
      preLoaderRoute: typeof AuthAppPlayersRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/playerPairs': {
      id: '/_auth/app/playerPairs'
      path: '/playerPairs'
      fullPath: '/app/playerPairs'
      preLoaderRoute: typeof AuthAppPlayerPairsRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/admin/users': {
      id: '/_auth/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthAdminUsersRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/app/tournaments/': {
      id: '/_auth/app/tournaments/'
      path: '/tournaments'
      fullPath: '/app/tournaments/'
      preLoaderRoute: typeof AuthAppTournamentsIndexRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/matches/$matchId': {
      id: '/_auth/app/matches/$matchId'
      path: '/matches/$matchId'
      fullPath: '/app/matches/$matchId'
      preLoaderRoute: typeof AuthAppMatchesMatchIdRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/tournaments/$slug/': {
      id: '/_auth/app/tournaments/$slug/'
      path: '/tournaments/$slug'
      fullPath: '/app/tournaments/$slug/'
      preLoaderRoute: typeof AuthAppTournamentsSlugIndexRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/brackets/$bracketId/': {
      id: '/_auth/app/brackets/$bracketId/'
      path: '/brackets/$bracketId'
      fullPath: '/app/brackets/$bracketId/'
      preLoaderRoute: typeof AuthAppBracketsBracketIdIndexRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/tournaments/$slug/categories/$categoryId/': {
      id: '/_auth/app/tournaments/$slug/categories/$categoryId/'
      path: '/tournaments/$slug/categories/$categoryId'
      fullPath: '/app/tournaments/$slug/categories/$categoryId/'
      preLoaderRoute: typeof AuthAppTournamentsSlugCategoriesCategoryIdIndexRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
  }
}

interface AuthAdminRouteRouteChildren {
  AuthAdminUsersRoute: typeof AuthAdminUsersRoute
  AuthAdminIndexRoute: typeof AuthAdminIndexRoute
}

const AuthAdminRouteRouteChildren: AuthAdminRouteRouteChildren = {
  AuthAdminUsersRoute: AuthAdminUsersRoute,
  AuthAdminIndexRoute: AuthAdminIndexRoute,
}

const AuthAdminRouteRouteWithChildren = AuthAdminRouteRoute._addFileChildren(
  AuthAdminRouteRouteChildren,
)

interface AuthAppRouteRouteChildren {
  AuthAppPlayerPairsRoute: typeof AuthAppPlayerPairsRoute
  AuthAppPlayersRoute: typeof AuthAppPlayersRoute
  AuthAppIndexRoute: typeof AuthAppIndexRoute
  AuthAppMatchesMatchIdRoute: typeof AuthAppMatchesMatchIdRoute
  AuthAppTournamentsIndexRoute: typeof AuthAppTournamentsIndexRoute
  AuthAppBracketsBracketIdIndexRoute: typeof AuthAppBracketsBracketIdIndexRoute
  AuthAppTournamentsSlugIndexRoute: typeof AuthAppTournamentsSlugIndexRoute
  AuthAppTournamentsSlugCategoriesCategoryIdIndexRoute: typeof AuthAppTournamentsSlugCategoriesCategoryIdIndexRoute
}

const AuthAppRouteRouteChildren: AuthAppRouteRouteChildren = {
  AuthAppPlayerPairsRoute: AuthAppPlayerPairsRoute,
  AuthAppPlayersRoute: AuthAppPlayersRoute,
  AuthAppIndexRoute: AuthAppIndexRoute,
  AuthAppMatchesMatchIdRoute: AuthAppMatchesMatchIdRoute,
  AuthAppTournamentsIndexRoute: AuthAppTournamentsIndexRoute,
  AuthAppBracketsBracketIdIndexRoute: AuthAppBracketsBracketIdIndexRoute,
  AuthAppTournamentsSlugIndexRoute: AuthAppTournamentsSlugIndexRoute,
  AuthAppTournamentsSlugCategoriesCategoryIdIndexRoute:
    AuthAppTournamentsSlugCategoriesCategoryIdIndexRoute,
}

const AuthAppRouteRouteWithChildren = AuthAppRouteRoute._addFileChildren(
  AuthAppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthAdminRouteRoute: typeof AuthAdminRouteRouteWithChildren
  AuthAppRouteRoute: typeof AuthAppRouteRouteWithChildren
  AuthGIdRoute: typeof AuthGIdRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAdminRouteRoute: AuthAdminRouteRouteWithChildren,
  AuthAppRouteRoute: AuthAppRouteRouteWithChildren,
  AuthGIdRoute: AuthGIdRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface GuestRouteRouteChildren {
  GuestLoginRoute: typeof GuestLoginRoute
  GuestSignupRoute: typeof GuestSignupRoute
}

const GuestRouteRouteChildren: GuestRouteRouteChildren = {
  GuestLoginRoute: GuestLoginRoute,
  GuestSignupRoute: GuestSignupRoute,
}

const GuestRouteRouteWithChildren = GuestRouteRoute._addFileChildren(
  GuestRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  GuestRouteRoute: GuestRouteRouteWithChildren,
  ShowcaseRoute: ShowcaseRoute,
  PublicIndexRoute: PublicIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
