/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShowcaseRouteImport } from './routes/showcase'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as GuestRouteRouteImport } from './routes/_guest/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as ScoreMatchIdRouteImport } from './routes/score.$matchId'
import { Route as GuestSignupRouteImport } from './routes/_guest/signup'
import { Route as GuestLoginRouteImport } from './routes/_guest/login'
import { Route as AuthAppRouteRouteImport } from './routes/_auth/app/route'
import { Route as AuthAdminRouteRouteImport } from './routes/_auth/admin/route'
import { Route as PublicTournamentsIndexRouteImport } from './routes/_public/tournaments.index'
import { Route as AuthAppIndexRouteImport } from './routes/_auth/app/index'
import { Route as AuthAdminIndexRouteImport } from './routes/_auth/admin/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as PublicTournamentsSlugRouteImport } from './routes/_public/tournaments.$slug'
import { Route as AuthAppPlayersRouteImport } from './routes/_auth/app/players'
import { Route as AuthAppPlayerPairsRouteImport } from './routes/_auth/app/player-pairs'
import { Route as AuthAdminUsersRouteImport } from './routes/_auth/admin/users'
import { Route as AuthAdminTournamentsRouteImport } from './routes/_auth/admin/tournaments'
import { Route as AuthAppTournamentsIndexRouteImport } from './routes/_auth/app/tournaments.index'
import { Route as AuthAppScorerIdRouteImport } from './routes/_auth/app/scorer.$id'
import { Route as AuthAppTournamentsSlugIndexRouteImport } from './routes/_auth/app/tournaments.$slug.index'
import { Route as AuthAppTournamentsSlugCategoriesCategoryIdIndexRouteImport } from './routes/_auth/app/tournaments.$slug.categories.$categoryId.index'
import { Route as AuthAppTournamentsSlugCategoriesCategoryIdMatchesMatchIdIndexRouteImport } from './routes/_auth/app/tournaments.$slug.categories.$categoryId.matches.$matchId.index'
import { Route as AuthAppTournamentsSlugCategoriesCategoryIdBracketsBracketIdIndexRouteImport } from './routes/_auth/app/tournaments.$slug.categories.$categoryId.brackets.$bracketId.index'

const ShowcaseRoute = ShowcaseRouteImport.update({
  id: '/showcase',
  path: '/showcase',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRouteRoute = GuestRouteRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const ScoreMatchIdRoute = ScoreMatchIdRouteImport.update({
  id: '/score/$matchId',
  path: '/score/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestSignupRoute = GuestSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => GuestRouteRoute,
} as any)
const GuestLoginRoute = GuestLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GuestRouteRoute,
} as any)
const AuthAppRouteRoute = AuthAppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAdminRouteRoute = AuthAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthRouteRoute,
} as any)
const PublicTournamentsIndexRoute = PublicTournamentsIndexRouteImport.update({
  id: '/tournaments/',
  path: '/tournaments/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AuthAppIndexRoute = AuthAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAdminIndexRoute = AuthAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAdminRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicTournamentsSlugRoute = PublicTournamentsSlugRouteImport.update({
  id: '/tournaments/$slug',
  path: '/tournaments/$slug',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AuthAppPlayersRoute = AuthAppPlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppPlayerPairsRoute = AuthAppPlayerPairsRouteImport.update({
  id: '/player-pairs',
  path: '/player-pairs',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAdminUsersRoute = AuthAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthAdminRouteRoute,
} as any)
const AuthAdminTournamentsRoute = AuthAdminTournamentsRouteImport.update({
  id: '/tournaments',
  path: '/tournaments',
  getParentRoute: () => AuthAdminRouteRoute,
} as any)
const AuthAppTournamentsIndexRoute = AuthAppTournamentsIndexRouteImport.update({
  id: '/tournaments/',
  path: '/tournaments/',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppScorerIdRoute = AuthAppScorerIdRouteImport.update({
  id: '/scorer/$id',
  path: '/scorer/$id',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppTournamentsSlugIndexRoute =
  AuthAppTournamentsSlugIndexRouteImport.update({
    id: '/tournaments/$slug/',
    path: '/tournaments/$slug/',
    getParentRoute: () => AuthAppRouteRoute,
  } as any)
const AuthAppTournamentsSlugCategoriesCategoryIdIndexRoute =
  AuthAppTournamentsSlugCategoriesCategoryIdIndexRouteImport.update({
    id: '/tournaments/$slug/categories/$categoryId/',
    path: '/tournaments/$slug/categories/$categoryId/',
    getParentRoute: () => AuthAppRouteRoute,
  } as any)
const AuthAppTournamentsSlugCategoriesCategoryIdMatchesMatchIdIndexRoute =
  AuthAppTournamentsSlugCategoriesCategoryIdMatchesMatchIdIndexRouteImport.update(
    {
      id: '/tournaments/$slug/categories/$categoryId/matches/$matchId/',
      path: '/tournaments/$slug/categories/$categoryId/matches/$matchId/',
      getParentRoute: () => AuthAppRouteRoute,
    } as any,
  )
const AuthAppTournamentsSlugCategoriesCategoryIdBracketsBracketIdIndexRoute =
  AuthAppTournamentsSlugCategoriesCategoryIdBracketsBracketIdIndexRouteImport.update(
    {
      id: '/tournaments/$slug/categories/$categoryId/brackets/$bracketId/',
      path: '/tournaments/$slug/categories/$categoryId/brackets/$bracketId/',
      getParentRoute: () => AuthAppRouteRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/showcase': typeof ShowcaseRoute
  '/admin': typeof AuthAdminRouteRouteWithChildren
  '/app': typeof AuthAppRouteRouteWithChildren
  '/login': typeof GuestLoginRoute
  '/signup': typeof GuestSignupRoute
  '/score/$matchId': typeof ScoreMatchIdRoute
  '/admin/tournaments': typeof AuthAdminTournamentsRoute
  '/admin/users': typeof AuthAdminUsersRoute
  '/app/player-pairs': typeof AuthAppPlayerPairsRoute
  '/app/players': typeof AuthAppPlayersRoute
  '/tournaments/$slug': typeof PublicTournamentsSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/': typeof AuthAdminIndexRoute
  '/app/': typeof AuthAppIndexRoute
  '/tournaments/': typeof PublicTournamentsIndexRoute
  '/app/scorer/$id': typeof AuthAppScorerIdRoute
  '/app/tournaments/': typeof AuthAppTournamentsIndexRoute
  '/app/tournaments/$slug/': typeof AuthAppTournamentsSlugIndexRoute
  '/app/tournaments/$slug/categories/$categoryId/': typeof AuthAppTournamentsSlugCategoriesCategoryIdIndexRoute
  '/app/tournaments/$slug/categories/$categoryId/brackets/$bracketId/': typeof AuthAppTournamentsSlugCategoriesCategoryIdBracketsBracketIdIndexRoute
  '/app/tournaments/$slug/categories/$categoryId/matches/$matchId/': typeof AuthAppTournamentsSlugCategoriesCategoryIdMatchesMatchIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/showcase': typeof ShowcaseRoute
  '/login': typeof GuestLoginRoute
  '/signup': typeof GuestSignupRoute
  '/score/$matchId': typeof ScoreMatchIdRoute
  '/admin/tournaments': typeof AuthAdminTournamentsRoute
  '/admin/users': typeof AuthAdminUsersRoute
  '/app/player-pairs': typeof AuthAppPlayerPairsRoute
  '/app/players': typeof AuthAppPlayersRoute
  '/tournaments/$slug': typeof PublicTournamentsSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin': typeof AuthAdminIndexRoute
  '/app': typeof AuthAppIndexRoute
  '/tournaments': typeof PublicTournamentsIndexRoute
  '/app/scorer/$id': typeof AuthAppScorerIdRoute
  '/app/tournaments': typeof AuthAppTournamentsIndexRoute
  '/app/tournaments/$slug': typeof AuthAppTournamentsSlugIndexRoute
  '/app/tournaments/$slug/categories/$categoryId': typeof AuthAppTournamentsSlugCategoriesCategoryIdIndexRoute
  '/app/tournaments/$slug/categories/$categoryId/brackets/$bracketId': typeof AuthAppTournamentsSlugCategoriesCategoryIdBracketsBracketIdIndexRoute
  '/app/tournaments/$slug/categories/$categoryId/matches/$matchId': typeof AuthAppTournamentsSlugCategoriesCategoryIdMatchesMatchIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_guest': typeof GuestRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/showcase': typeof ShowcaseRoute
  '/_auth/admin': typeof AuthAdminRouteRouteWithChildren
  '/_auth/app': typeof AuthAppRouteRouteWithChildren
  '/_guest/login': typeof GuestLoginRoute
  '/_guest/signup': typeof GuestSignupRoute
  '/score/$matchId': typeof ScoreMatchIdRoute
  '/_public/': typeof PublicIndexRoute
  '/_auth/admin/tournaments': typeof AuthAdminTournamentsRoute
  '/_auth/admin/users': typeof AuthAdminUsersRoute
  '/_auth/app/player-pairs': typeof AuthAppPlayerPairsRoute
  '/_auth/app/players': typeof AuthAppPlayersRoute
  '/_public/tournaments/$slug': typeof PublicTournamentsSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_auth/admin/': typeof AuthAdminIndexRoute
  '/_auth/app/': typeof AuthAppIndexRoute
  '/_public/tournaments/': typeof PublicTournamentsIndexRoute
  '/_auth/app/scorer/$id': typeof AuthAppScorerIdRoute
  '/_auth/app/tournaments/': typeof AuthAppTournamentsIndexRoute
  '/_auth/app/tournaments/$slug/': typeof AuthAppTournamentsSlugIndexRoute
  '/_auth/app/tournaments/$slug/categories/$categoryId/': typeof AuthAppTournamentsSlugCategoriesCategoryIdIndexRoute
  '/_auth/app/tournaments/$slug/categories/$categoryId/brackets/$bracketId/': typeof AuthAppTournamentsSlugCategoriesCategoryIdBracketsBracketIdIndexRoute
  '/_auth/app/tournaments/$slug/categories/$categoryId/matches/$matchId/': typeof AuthAppTournamentsSlugCategoriesCategoryIdMatchesMatchIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/showcase'
    | '/admin'
    | '/app'
    | '/login'
    | '/signup'
    | '/score/$matchId'
    | '/admin/tournaments'
    | '/admin/users'
    | '/app/player-pairs'
    | '/app/players'
    | '/tournaments/$slug'
    | '/api/auth/$'
    | '/admin/'
    | '/app/'
    | '/tournaments/'
    | '/app/scorer/$id'
    | '/app/tournaments/'
    | '/app/tournaments/$slug/'
    | '/app/tournaments/$slug/categories/$categoryId/'
    | '/app/tournaments/$slug/categories/$categoryId/brackets/$bracketId/'
    | '/app/tournaments/$slug/categories/$categoryId/matches/$matchId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/showcase'
    | '/login'
    | '/signup'
    | '/score/$matchId'
    | '/admin/tournaments'
    | '/admin/users'
    | '/app/player-pairs'
    | '/app/players'
    | '/tournaments/$slug'
    | '/api/auth/$'
    | '/admin'
    | '/app'
    | '/tournaments'
    | '/app/scorer/$id'
    | '/app/tournaments'
    | '/app/tournaments/$slug'
    | '/app/tournaments/$slug/categories/$categoryId'
    | '/app/tournaments/$slug/categories/$categoryId/brackets/$bracketId'
    | '/app/tournaments/$slug/categories/$categoryId/matches/$matchId'
  id:
    | '__root__'
    | '/_auth'
    | '/_guest'
    | '/_public'
    | '/showcase'
    | '/_auth/admin'
    | '/_auth/app'
    | '/_guest/login'
    | '/_guest/signup'
    | '/score/$matchId'
    | '/_public/'
    | '/_auth/admin/tournaments'
    | '/_auth/admin/users'
    | '/_auth/app/player-pairs'
    | '/_auth/app/players'
    | '/_public/tournaments/$slug'
    | '/api/auth/$'
    | '/_auth/admin/'
    | '/_auth/app/'
    | '/_public/tournaments/'
    | '/_auth/app/scorer/$id'
    | '/_auth/app/tournaments/'
    | '/_auth/app/tournaments/$slug/'
    | '/_auth/app/tournaments/$slug/categories/$categoryId/'
    | '/_auth/app/tournaments/$slug/categories/$categoryId/brackets/$bracketId/'
    | '/_auth/app/tournaments/$slug/categories/$categoryId/matches/$matchId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  GuestRouteRoute: typeof GuestRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  ShowcaseRoute: typeof ShowcaseRoute
  ScoreMatchIdRoute: typeof ScoreMatchIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/showcase': {
      id: '/showcase'
      path: '/showcase'
      fullPath: '/showcase'
      preLoaderRoute: typeof ShowcaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/score/$matchId': {
      id: '/score/$matchId'
      path: '/score/$matchId'
      fullPath: '/score/$matchId'
      preLoaderRoute: typeof ScoreMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest/signup': {
      id: '/_guest/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof GuestSignupRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_guest/login': {
      id: '/_guest/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof GuestLoginRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_auth/app': {
      id: '/_auth/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthAppRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/admin': {
      id: '/_auth/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthAdminRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_public/tournaments/': {
      id: '/_public/tournaments/'
      path: '/tournaments'
      fullPath: '/tournaments/'
      preLoaderRoute: typeof PublicTournamentsIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_auth/app/': {
      id: '/_auth/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthAppIndexRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/admin/': {
      id: '/_auth/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthAdminIndexRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/tournaments/$slug': {
      id: '/_public/tournaments/$slug'
      path: '/tournaments/$slug'
      fullPath: '/tournaments/$slug'
      preLoaderRoute: typeof PublicTournamentsSlugRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_auth/app/players': {
      id: '/_auth/app/players'
      path: '/players'
      fullPath: '/app/players'
      preLoaderRoute: typeof AuthAppPlayersRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/player-pairs': {
      id: '/_auth/app/player-pairs'
      path: '/player-pairs'
      fullPath: '/app/player-pairs'
      preLoaderRoute: typeof AuthAppPlayerPairsRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/admin/users': {
      id: '/_auth/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthAdminUsersRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/admin/tournaments': {
      id: '/_auth/admin/tournaments'
      path: '/tournaments'
      fullPath: '/admin/tournaments'
      preLoaderRoute: typeof AuthAdminTournamentsRouteImport
      parentRoute: typeof AuthAdminRouteRoute
    }
    '/_auth/app/tournaments/': {
      id: '/_auth/app/tournaments/'
      path: '/tournaments'
      fullPath: '/app/tournaments/'
      preLoaderRoute: typeof AuthAppTournamentsIndexRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/scorer/$id': {
      id: '/_auth/app/scorer/$id'
      path: '/scorer/$id'
      fullPath: '/app/scorer/$id'
      preLoaderRoute: typeof AuthAppScorerIdRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/tournaments/$slug/': {
      id: '/_auth/app/tournaments/$slug/'
      path: '/tournaments/$slug'
      fullPath: '/app/tournaments/$slug/'
      preLoaderRoute: typeof AuthAppTournamentsSlugIndexRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/tournaments/$slug/categories/$categoryId/': {
      id: '/_auth/app/tournaments/$slug/categories/$categoryId/'
      path: '/tournaments/$slug/categories/$categoryId'
      fullPath: '/app/tournaments/$slug/categories/$categoryId/'
      preLoaderRoute: typeof AuthAppTournamentsSlugCategoriesCategoryIdIndexRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/tournaments/$slug/categories/$categoryId/matches/$matchId/': {
      id: '/_auth/app/tournaments/$slug/categories/$categoryId/matches/$matchId/'
      path: '/tournaments/$slug/categories/$categoryId/matches/$matchId'
      fullPath: '/app/tournaments/$slug/categories/$categoryId/matches/$matchId/'
      preLoaderRoute: typeof AuthAppTournamentsSlugCategoriesCategoryIdMatchesMatchIdIndexRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/tournaments/$slug/categories/$categoryId/brackets/$bracketId/': {
      id: '/_auth/app/tournaments/$slug/categories/$categoryId/brackets/$bracketId/'
      path: '/tournaments/$slug/categories/$categoryId/brackets/$bracketId'
      fullPath: '/app/tournaments/$slug/categories/$categoryId/brackets/$bracketId/'
      preLoaderRoute: typeof AuthAppTournamentsSlugCategoriesCategoryIdBracketsBracketIdIndexRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
  }
}

interface AuthAdminRouteRouteChildren {
  AuthAdminTournamentsRoute: typeof AuthAdminTournamentsRoute
  AuthAdminUsersRoute: typeof AuthAdminUsersRoute
  AuthAdminIndexRoute: typeof AuthAdminIndexRoute
}

const AuthAdminRouteRouteChildren: AuthAdminRouteRouteChildren = {
  AuthAdminTournamentsRoute: AuthAdminTournamentsRoute,
  AuthAdminUsersRoute: AuthAdminUsersRoute,
  AuthAdminIndexRoute: AuthAdminIndexRoute,
}

const AuthAdminRouteRouteWithChildren = AuthAdminRouteRoute._addFileChildren(
  AuthAdminRouteRouteChildren,
)

interface AuthAppRouteRouteChildren {
  AuthAppPlayerPairsRoute: typeof AuthAppPlayerPairsRoute
  AuthAppPlayersRoute: typeof AuthAppPlayersRoute
  AuthAppIndexRoute: typeof AuthAppIndexRoute
  AuthAppScorerIdRoute: typeof AuthAppScorerIdRoute
  AuthAppTournamentsIndexRoute: typeof AuthAppTournamentsIndexRoute
  AuthAppTournamentsSlugIndexRoute: typeof AuthAppTournamentsSlugIndexRoute
  AuthAppTournamentsSlugCategoriesCategoryIdIndexRoute: typeof AuthAppTournamentsSlugCategoriesCategoryIdIndexRoute
  AuthAppTournamentsSlugCategoriesCategoryIdBracketsBracketIdIndexRoute: typeof AuthAppTournamentsSlugCategoriesCategoryIdBracketsBracketIdIndexRoute
  AuthAppTournamentsSlugCategoriesCategoryIdMatchesMatchIdIndexRoute: typeof AuthAppTournamentsSlugCategoriesCategoryIdMatchesMatchIdIndexRoute
}

const AuthAppRouteRouteChildren: AuthAppRouteRouteChildren = {
  AuthAppPlayerPairsRoute: AuthAppPlayerPairsRoute,
  AuthAppPlayersRoute: AuthAppPlayersRoute,
  AuthAppIndexRoute: AuthAppIndexRoute,
  AuthAppScorerIdRoute: AuthAppScorerIdRoute,
  AuthAppTournamentsIndexRoute: AuthAppTournamentsIndexRoute,
  AuthAppTournamentsSlugIndexRoute: AuthAppTournamentsSlugIndexRoute,
  AuthAppTournamentsSlugCategoriesCategoryIdIndexRoute:
    AuthAppTournamentsSlugCategoriesCategoryIdIndexRoute,
  AuthAppTournamentsSlugCategoriesCategoryIdBracketsBracketIdIndexRoute:
    AuthAppTournamentsSlugCategoriesCategoryIdBracketsBracketIdIndexRoute,
  AuthAppTournamentsSlugCategoriesCategoryIdMatchesMatchIdIndexRoute:
    AuthAppTournamentsSlugCategoriesCategoryIdMatchesMatchIdIndexRoute,
}

const AuthAppRouteRouteWithChildren = AuthAppRouteRoute._addFileChildren(
  AuthAppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthAdminRouteRoute: typeof AuthAdminRouteRouteWithChildren
  AuthAppRouteRoute: typeof AuthAppRouteRouteWithChildren
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAdminRouteRoute: AuthAdminRouteRouteWithChildren,
  AuthAppRouteRoute: AuthAppRouteRouteWithChildren,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface GuestRouteRouteChildren {
  GuestLoginRoute: typeof GuestLoginRoute
  GuestSignupRoute: typeof GuestSignupRoute
}

const GuestRouteRouteChildren: GuestRouteRouteChildren = {
  GuestLoginRoute: GuestLoginRoute,
  GuestSignupRoute: GuestSignupRoute,
}

const GuestRouteRouteWithChildren = GuestRouteRoute._addFileChildren(
  GuestRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicIndexRoute: typeof PublicIndexRoute
  PublicTournamentsSlugRoute: typeof PublicTournamentsSlugRoute
  PublicTournamentsIndexRoute: typeof PublicTournamentsIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicIndexRoute: PublicIndexRoute,
  PublicTournamentsSlugRoute: PublicTournamentsSlugRoute,
  PublicTournamentsIndexRoute: PublicTournamentsIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  GuestRouteRoute: GuestRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
  ShowcaseRoute: ShowcaseRoute,
  ScoreMatchIdRoute: ScoreMatchIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
